### ISSUE TITLE
Tio1608-D Support

### ISSUE THREAD

**Issue by BB21B** [bitfocus/companion-module-yamaha-rcp#22]
Hi all,

I'm about to get my hands on a Tio1608-D and it appears that it uses the same SCP protocol format on port 49280.

There is a Crestron module and some documentation that suggests this.

The idea would be to be able to set gains and phantom power.
Feedback and variables would be useful too.

This would also be compatible with:
Rio3224-D, Rio1608-D, Ri8-D, Ro8-D, Rsio64-D, RMio64-D, Rio3224-D2 and Rio1608-D2

Which are all controllable with Yamaha R Remote.

Let me know if it looks possible and I'll see if I can figure it out and put in a PR when I get the hardware.

Thanks

https://uk.yamaha.com/en/products/proaudio/interfaces/tio1608-d/downloads.html#product-tabs

[YamahaTIOModule_V1.1.pdf](https://github.com/bitfocus/companion-module-yamaha-scp/files/6804363/YamahaTIOModule_V1.1.pdf)

**Comment by MeestorX** [comment]
You’d like to add support for those devices? You’ll need the protocol info for them.
My next update for the SCP module will be quite significant, adding Rivage support as well as the new feedback, step actions and so on.

**Comment by BB21B** [comment]
@MeestorX is the command and control format pretty standardised between devices?

I'll have a read through the code anyway, but maybe hold off until you've pushed your update before I start to tinker. But yes I would be interested in implementing this.

**Comment by MeestorX** [comment]
Yes, the commands for matching operations are the same, except for the specific parameters for each device. However, the I/O unites will have commands that don't exist on the consoles, and vice-versa. Do you have the command and parameter list for the devices you wish to control?

**Comment by BB21B** [comment]
Only what is referenced in the Crestron docs. I'll reach out and if that is no good I'll fire up Wireshark and go from there.

**Comment by BB21B** [comment]
I have the device now and I've just scraped most of the commands from it that I would need. I'll look into implementing soon

```
//Input 16 Phantom On
set IO:Current/InCh/48VOn 15 0 1
//Input 16 Phantom Off
set IO:Current/InCh/48VOn 15 0 0


//Input 16 30dB Gain (Max 66 min -6)
set IO:Current/InCh/HAGain 15 0 30
//Input 16 -6dB Gain
set IO:Current/InCh/HAGain 15 0 -6

//Input 16 HPF On
set IO:Current/InCh/HPFOn 15 0 1
//Input 16 HPF Off
set IO:Current/InCh/HPFOn 15 0 0

//Input 16 HPF Freq to 20Hz (Max 600, min 20 in Hz)
set IO:Current/InCh/HPFFreq 15 0 20
//Input 16 HPF Freq to 600Hz (Max 600, min 20 in Hz)
set IO:Current/InCh/HPFFreq 15 0 600

//INPUT LEVELS
NOTIFY mtr IO:Current/Dev/InputLevel level 22 21 20 20 20 20 20 20 20 20 20 20 20 20 20 20
NOTIFY mtr IO:Current/Dev/InputLevel level 22 20 20 20 1f 20 20 20 20 20 20 20 20 20 20 20

//Example GET
get IO:Current/InCh/48VOn 8 0
OK get IO:Current/InCh/48VOn 8 0 0

devinfo
OK devinfo paramsetver "Tio:1.0.0, IO:1.0.0"

devinfo version
OK devinfo version "1.04.0"

devinfo productname
OK devinfo productname "Tio1608-D"

devinfo inputport
OK devinfo inputport "16"

devinfo outputport
OK devinfo outputport "8"

scpmode keepalive 10000
OK scpmode keepalive 10000

```

**Comment by MeestorX** [comment]
Great job.
The next push is coming shortly. Significant changes, and Yamaha needs the name of the module to change. (don't ask...)

**Comment by BB21B** [comment]
Thanks @MeestorX I just added the prminfo too I noticed those commands from your txt files in the repo. So it should be pretty complete now. I'll follow awaiting the update

**Comment by MeestorX** [comment]
Nice.

If you felt like it, you could join my discourse group where there's people that can beta test and give feedback.

discourse.remotely-possible.ca

**Comment by MeestorX** [comment]
And the latest builds are there too.

**Comment by MeestorX** [comment]
New build up today (Aug 1st).

Maybe drop me a line on the forum and let me know if it works for you and we can discuss how to best add the TIO functions.
