### ISSUE TITLE
Feedback Instance

### ISSUE THREAD

**Issue by kaw480** [bitfocus/companion-module-yamaha-rcp#24]
running version 1.4.1  For scene recall, instance feedback works for scene a 01, but a 02 and a 03 dont update when changed.  The console is a yamaha tf3 with firmware 4.01  Companion version is 2.1.2

this if the info from recalling scene 1 then 2 then 3

09. 12:01:29 device(CL46I1A02628): Button 6.5 released
09. 12:01:29 instance(Yamaha TF Media Room): Received from device: 'NOTIFY sscurrent_ex scene_a 3 unmodified'
09. 12:01:29 instance(Yamaha TF Media Room): Received from device: 'OK ssrecall_ex scene_a 3'
09. 12:01:29 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 2 unmodified'
09. 12:01:29 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 2 unmodified'
09. 12:01:29 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 2 unmodified'
09. 12:01:29 instance(Yamaha TF Media Room): Received from device: 'OK get MIXER:Current/MuteMaster/On 0 0 0'
09. 12:01:29 device(CL46I1A02628): Button 6.5 pressed
09. 12:01:29 instance(Yamaha TF Media Room): sending 'ssrecall_ex scene_a 3' to 10.0.1.75
09. 12:01:29 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:29 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:29 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:29 instance(Yamaha TF Media Room): sending 'get MIXER:Current/MuteMaster/On 0 0' to 10.0.1.75
09. 12:01:27 device(CL46I1A02628): Button 6.4 released
09. 12:01:27 instance(Yamaha TF Media Room): Received from device: 'NOTIFY sscurrent_ex scene_a 2 unmodified'
09. 12:01:27 instance(Yamaha TF Media Room): Received from device: 'OK ssrecall_ex scene_a 2'
09. 12:01:27 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 1 unmodified'
09. 12:01:27 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 1 unmodified'
09. 12:01:27 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 1 unmodified'
09. 12:01:26 instance(Yamaha TF Media Room): Received from device: 'OK get MIXER:Current/MuteMaster/On 0 0 0'
09. 12:01:26 device(CL46I1A02628): Button 6.4 pressed
09. 12:01:26 instance(Yamaha TF Media Room): sending 'ssrecall_ex scene_a 2' to 10.0.1.75
09. 12:01:26 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:26 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:26 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:26 instance(Yamaha TF Media Room): sending 'get MIXER:Current/MuteMaster/On 0 0' to 10.0.1.75
09. 12:01:22 device(CL46I1A02628): Button 6.3 released
09. 12:01:22 instance(Yamaha TF Media Room): Received from device: 'NOTIFY sscurrent_ex scene_a 1 unmodified'
09. 12:01:22 instance(Yamaha TF Media Room): Received from device: 'OK ssrecall_ex scene_a 1'
09. 12:01:22 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 2 unmodified'
09. 12:01:22 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 2 unmodified'
09. 12:01:22 instance(Yamaha TF Media Room): Received from device: 'OK sscurrent_ex scene_a 2 unmodified'
09. 12:01:22 instance(Yamaha TF Media Room): Received from device: 'OK get MIXER:Current/MuteMaster/On 0 0 0'
09. 12:01:22 device(CL46I1A02628): Button 6.3 pressed
09. 12:01:22 instance(Yamaha TF Media Room): sending 'ssrecall_ex scene_a 1' to 10.0.1.75
09. 12:01:22 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:22 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:22 instance(Yamaha TF Media Room): sending 'sscurrent_ex scene_a' to 10.0.1.75
09. 12:01:22 instance(Yamaha TF Media Room): sending 'get MIXER:Current/MuteMaster/On 0 0' to 10.0.1.75

**Comment by MeestorX** [comment]
Happy to resolve this with you but I'll need more info. Hit me up at my forum and please post your configuration file.
https://discourse.checkcheckonetwo.com
