### ISSUE TITLE
Yamaha RCP - No control of InCh/ToMono/On

### ISSUE THREAD

**Issue by mrderkis** [bitfocus/companion-module-yamaha-rcp#25]
Unless I am missing something, I am unable to turn on the channels sending the Mono Channel. We use this as a failsafe in case Waves Tune crashes, we can press one button to send the Raw Microphone audio to the mono channel.

**Comment by MeestorX** [comment]
That command only exists for the TF consoles. There is no command like that for the CL/QL or Rivage you'll be out of luck.

**Comment by mrderkis** [comment]
Thank you for your feedback. Is that just the way RCP works? On the custom companion build (YamahaCL-MIDI), it does have the InCh/ToMono/On control. I’m currently back to using that one for this feature which is perfectly fine for my set up but I’m mostly just curious as I am mostly unfamiliar with the different protocols. Thank you.

**Comment by MeestorX** [comment]
Yes, RCP has only a limited number of commands and each console type has it's own set.
If you're using a CL or QL, you'll want to use the MIDI module, it's much more powerful.

**Comment by mrderkis** [comment]
Thank you for your help! The modules have been a game changer. Have a great one!

**Comment by MeestorX** [comment]
Thank you for your kind words!
Enjoy.
