### ISSUE TITLE
Yamaha LS9

### ISSUE THREAD

**Issue by TomEagle** [bitfocus/companion-module-yamaha-rcp#26]
Is there a way to control Yamaha LS9.

**Comment by MeestorX** [comment]
Not with this module. The LS9 and M7CL use MIDI over TCP for control, and a different protocol.

**Comment by TomEagle** [comment]
Is there a  module that will do MIDI over TCP that can be used to control Yamaha LS9. I have two that I would like to control while Live Streaming. Thanks,

**Comment by MeestorX** [comment]
Not at the moment. However, if this is something worth $$ to you, contact me at my website. 
Honestly though, it would probably be cheaper and better in the long run to retire the LS9 and get a newer console. Just my 2¢.
