### ISSUE TITLE
How to update to a certain version?

### ISSUE THREAD

**Issue by robertl87** [bitfocus/companion-module-yamaha-rcp#27]
I think I'm in need of v1.6.3 for the bug fix for Scene Recall. How does this work? Can I manually import this module on my PC? Or how can I find out in which Companion release it is included?

**Comment by MeestorX** [comment]
You can download the latest build at discourse.checkcheckonetwo.com
It may be a while before it’s added to an official release as I need to be sure there’s no new bugs.

**Comment by robertl87** [comment]
Ah, it seems I have to register and gain some level to download. Let me try that out. Thanks!

**Comment by MeestorX** [comment]
https://i.kym-cdn.com/photos/images/newsfeed/001/653/546/4b2.jpg
