### ISSUE TITLE
[FEATURE REQUEST] Playback USB Audio

### ISSUE THREAD

**Issue by ZachIndigo** [bitfocus/companion-module-yamaha-rcp#29]
Companion Version: 2.2.0+3998-ccea40c7
Device: Yamaha CL1 mixer

I am using a Yamaha CL1 for my workplace, and we have a couple of audio files that we need to play at specified times. I would like to have a macro for a) playing the track, and then b) fading in the audio. However, I cannot find a way to do that in Companion, and using the "Record RCP Macro" option will not record playing the track, just changing the volume.

**Comment by MeestorX** [comment]
Yamaha has not made an RCP command for that function. If they do, then I can implement it. Please feel free to ask Yamaha to add it!

**Comment by MeestorX** [comment]
You can do what you want however by linking playback to a scene recall. You can use the fade function as well when changing scenes.

**Comment by ZachIndigo** [comment]
How does one link playback to scene recall?

**Comment by MeestorX** [comment]
Pg. 99 in the manual.
https://usa.yamaha.com/files/download/other_assets/1/392941/cl5_3_1_en_rm_d1.pdf
