### ISSUE TITLE
Feature idea - transport controls

### ISSUE THREAD

**Issue by slm265** [bitfocus/companion-module-yamaha-rcp#30]
Hi,
Just come back from a regular job where I have record all sessions of a conference to the USB stick.  I normally set user keys to be "Record & Start" and "Stop" to speed up the process (while I reset countdown timers, change mics, advance PPT all at the same time).  If the transport controls for my QL were in the module, I could have one button which could stop the current record, wait, start a new record, and run the next countdown cue from CueTimer, halving the workload.  Any help with this would be really appreciated.

S

**Comment by MeestorX** [comment]
Yamaha has not added the transport controls to the RCP protocol. The best way to get this functionality added is to send a feature request to Yamaha. If enough people ask, then perhaps they would add it.

**Comment by slm265** [comment]
Thanks Andrew, just pinged a feature request across to Yamaha, fingers crossed!
