### ISSUE TITLE
CL/QL Inserts

### ISSUE THREAD

**Issue by MeandtheDevilknockingonyourdoor** [bitfocus/companion-module-yamaha-rcp#31]
Hey Andi,

I used before ur Midi build and I really loved the function InsertON for Ch/Mix/Mtrx.
In this build I can't find this only for rivage.... does the rivage and the CL/QL commands work for booth of them?

Thx Martin

**Comment by MeestorX** [comment]
Each console has a different set of commands. Insert On/Off is not one of the RCP commands on the CL/QL, but it is on the Rivage.
The easiest way to verify if a console supports a certain command is to look at the log page. With the debug button pressed, you'll see every message that is set to and comes from the console. When on that page, perform any function on the console - move a fader or press the insert on/off on the console and see if it shows a message. If a function doesn't show a message then it's not supported on that console.
If you need to use Insert On/Off on the CL/QL, then you'll need to use the MIDI module, downloadable from my website. https://discourse.checkcheckonetwo.com
