### ISSUE TITLE
Input/CH/Level to "-32768" imports as "0"

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-yamaha-rcp#32]
FINALLY getting around to updating to V3 and it looks like my commands to send a fader to -32768 for OFF are importing to 0 instead at least in the latest builds.  Not sure if this a new issue as I'm just now digging into the 3.0 builds.

**Comment by MeestorX** [comment]
Ah! I changed the values to show actual dB numbers in v3 so -32768 is actually "-inf" (negative infinity) on v3.
I'll have to look at the upgradescript to see why it's not doing that conversion.
If you can send me your v2 .companionconfig file via the forum (discourse.checkcheckonetwo.com), I can test it to make sure it converts correctly.

**Comment by MeestorX** [comment]
I just tested this and the import does work correctly on my machine. As I say, I'd be happy to test importing your config if you want to send it to me.
Closing this issue for now.
